# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lda.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lda.proto',
  package='lda',
  serialized_pb='\n\tlda.proto\x12\x03lda\"!\n\x04Word\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05topic\x18\x02 \x01(\x05\"&\n\nDocumentPB\x12\x18\n\x05words\x18\x01 \x03(\x0b\x32\t.lda.Word\"\'\n\x07NonZero\x12\r\n\x05topic\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"9\n\x16SparseTopicHistogramPB\x12\x1f\n\tnon_zeros\x18\x01 \x03(\x0b\x32\x0c.lda.NonZero\"\\\n\x14WordTopicHistogramPB\x12\x0c\n\x04word\x18\x01 \x01(\x05\x12\x36\n\x11sparse_topic_hist\x18\x02 \x01(\x0b\x32\x1b.lda.SparseTopicHistogramPB\".\n\x16GlobalTopicHistogramPB\x12\x14\n\x0ctopic_counts\x18\x01 \x03(\x03\"8\n\rHyperParamsPB\x12\x13\n\x0btopic_prior\x18\x01 \x01(\x01\x12\x12\n\nword_prior\x18\x02 \x01(\x01')




_WORD = _descriptor.Descriptor(
  name='Word',
  full_name='lda.Word',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='lda.Word.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topic', full_name='lda.Word.topic', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=51,
)


_DOCUMENTPB = _descriptor.Descriptor(
  name='DocumentPB',
  full_name='lda.DocumentPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='words', full_name='lda.DocumentPB.words', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=53,
  serialized_end=91,
)


_NONZERO = _descriptor.Descriptor(
  name='NonZero',
  full_name='lda.NonZero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='lda.NonZero.topic', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='lda.NonZero.count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=93,
  serialized_end=132,
)


_SPARSETOPICHISTOGRAMPB = _descriptor.Descriptor(
  name='SparseTopicHistogramPB',
  full_name='lda.SparseTopicHistogramPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='non_zeros', full_name='lda.SparseTopicHistogramPB.non_zeros', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=134,
  serialized_end=191,
)


_WORDTOPICHISTOGRAMPB = _descriptor.Descriptor(
  name='WordTopicHistogramPB',
  full_name='lda.WordTopicHistogramPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='lda.WordTopicHistogramPB.word', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sparse_topic_hist', full_name='lda.WordTopicHistogramPB.sparse_topic_hist', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=193,
  serialized_end=285,
)


_GLOBALTOPICHISTOGRAMPB = _descriptor.Descriptor(
  name='GlobalTopicHistogramPB',
  full_name='lda.GlobalTopicHistogramPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic_counts', full_name='lda.GlobalTopicHistogramPB.topic_counts', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=287,
  serialized_end=333,
)


_HYPERPARAMSPB = _descriptor.Descriptor(
  name='HyperParamsPB',
  full_name='lda.HyperParamsPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic_prior', full_name='lda.HyperParamsPB.topic_prior', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='word_prior', full_name='lda.HyperParamsPB.word_prior', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=335,
  serialized_end=391,
)

_DOCUMENTPB.fields_by_name['words'].message_type = _WORD
_SPARSETOPICHISTOGRAMPB.fields_by_name['non_zeros'].message_type = _NONZERO
_WORDTOPICHISTOGRAMPB.fields_by_name['sparse_topic_hist'].message_type = _SPARSETOPICHISTOGRAMPB
DESCRIPTOR.message_types_by_name['Word'] = _WORD
DESCRIPTOR.message_types_by_name['DocumentPB'] = _DOCUMENTPB
DESCRIPTOR.message_types_by_name['NonZero'] = _NONZERO
DESCRIPTOR.message_types_by_name['SparseTopicHistogramPB'] = _SPARSETOPICHISTOGRAMPB
DESCRIPTOR.message_types_by_name['WordTopicHistogramPB'] = _WORDTOPICHISTOGRAMPB
DESCRIPTOR.message_types_by_name['GlobalTopicHistogramPB'] = _GLOBALTOPICHISTOGRAMPB
DESCRIPTOR.message_types_by_name['HyperParamsPB'] = _HYPERPARAMSPB

class Word(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORD

  # @@protoc_insertion_point(class_scope:lda.Word)

class DocumentPB(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCUMENTPB

  # @@protoc_insertion_point(class_scope:lda.DocumentPB)

class NonZero(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NONZERO

  # @@protoc_insertion_point(class_scope:lda.NonZero)

class SparseTopicHistogramPB(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPARSETOPICHISTOGRAMPB

  # @@protoc_insertion_point(class_scope:lda.SparseTopicHistogramPB)

class WordTopicHistogramPB(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORDTOPICHISTOGRAMPB

  # @@protoc_insertion_point(class_scope:lda.WordTopicHistogramPB)

class GlobalTopicHistogramPB(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GLOBALTOPICHISTOGRAMPB

  # @@protoc_insertion_point(class_scope:lda.GlobalTopicHistogramPB)

class HyperParamsPB(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HYPERPARAMSPB

  # @@protoc_insertion_point(class_scope:lda.HyperParamsPB)


# @@protoc_insertion_point(module_scope)
